pipelines:
  web-microservice:
    group: web-microservices
    materials:
      source:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rawmind0/web-microservice.git
      inventory:
        pipeline: web-inventory
        stage: release
      payments:
        pipeline: web-payments
        stage: release
      shipping:
        pipeline: web-shipping
        stage: release
      gateway:
        pipeline: web-gateway
        stage: release
    stages:
      - release: # name of stage
          fetch_materials: yes
          keep_artifacts: no
          clean_workspace: yes
          jobs:
            release: # name of the job
              artifacts:
                - build:
                    source: docker-compose.yml
                    destination: 
                - build:
                    source: rancher-compose.yml
                    destination: 
              tasks:
                - fetch:
                    pipeline: web-inventory
                    stage: release
                    job: release
                    is_file: yes
                    source: ci/released_version
                    destination: inventory
                - fetch:
                    pipeline: web-payments
                    stage: release
                    job: release
                    is_file: yes
                    source: ci/released_version
                    destination: payments
                - fetch:
                    pipeline: web-shipping
                    stage: release
                    job: release
                    is_file: yes
                    source: ci/released_version
                    destination: shipping
                - fetch:
                    pipeline: web-gateway
                    stage: release
                    job: release
                    is_file: yes
                    source: ci/released_version
                    destination: gateway
                - script: | 
                    echo inventory
                    echo payments
                    echo shipping
                    echo gateway
                    ./docker-compose.yml.tmpl
                    ./rancher-compose.yml.tmpl

